-- =====================================================
-- Phase 1, Step 2: Drop Bloated Indexes
-- Run during: OFF-HOURS MAINTENANCE WINDOW ONLY
-- Run AFTER: 01-pre-check-validation.sql (save its output first)
-- Expected duration: ~15-30 minutes
-- Risk: LOW — indexes are not data, no rows are modified
-- Rollback: Re-run 06-rollback.sql
-- =====================================================

-- =====================================================
-- DeviceSummaries — 3 known bloated indexes
-- =====================================================

-- Index 1: IX_DeviceSummaries_DeviceId
-- REASON: Contains 26 columns in the key — this is NOT an index,
-- it's a full copy of the table. Every INSERT writes ~24KB to this index.
-- This index was likely auto-generated or added speculatively and never
-- cleaned up. Dropping it will reduce per-ping write amplification by ~15%.
PRINT 'Dropping IX_DeviceSummaries_DeviceId (26 columns)...'
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DeviceSummaries_DeviceId' AND object_id = OBJECT_ID('DeviceSummaries'))
    DROP INDEX IX_DeviceSummaries_DeviceId ON DeviceSummaries;
PRINT 'Done.'
GO

-- Index 2: nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6
-- REASON: Contains 20 columns. Overlaps heavily with the other bloated
-- indexes. Auto-generated by the Azure SQL workload advisor based on a
-- query that was likely a one-time report. The query patterns it served
-- are now covered by the retained indexes and the new optimized index.
PRINT 'Dropping nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6 (20 columns)...'
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6' AND object_id = OBJECT_ID('DeviceSummaries'))
    DROP INDEX nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6 ON DeviceSummaries;
PRINT 'Done.'
GO

-- Index 3: nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1
-- REASON: Single column index on ExcursionTimeRunning only — likely from
-- one-off query tuning. Not used by any stored procedure regularly.
-- Queries filtering by ExcursionTimeRunning alone have no selective compound
-- key to leverage; the clustered PK is sufficient for such ad-hoc lookups.
PRINT 'Dropping nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1 (ExcursionTimeRunning only)...'
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1' AND object_id = OBJECT_ID('DeviceSummaries'))
    DROP INDEX nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1 ON DeviceSummaries;
PRINT 'Done.'
GO

-- =====================================================
-- DeviceEvents — drop bloated non-clustered indexes
--
-- ACTION REQUIRED BEFORE RUNNING:
-- Review the output of Section 3 (DeviceEvents index inventory) saved from
-- 01-pre-check-validation.sql.
--
-- For each non-clustered index that:
--   a) Has 10+ INCLUDE columns (wide covering index), OR
--   b) Has user_updates >> user_seeks (write-heavy, rarely-read)
--
-- Add a DROP block following the pattern below, replacing
-- [FILL_IN_FROM_PRE_CHECK] with the actual index name.
--
-- Do NOT drop:
--   - The clustered primary key index
--   - Unique constraint indexes
--   - Indexes with user_seeks > 100 and no obvious bloat
-- =====================================================

-- Example block (copy and repeat for each bloated index found):
-- PRINT 'Dropping [FILL_IN_FROM_PRE_CHECK] on DeviceEvents...'
-- IF EXISTS (SELECT 1 FROM sys.indexes
--            WHERE name = '[FILL_IN_FROM_PRE_CHECK]'
--              AND object_id = OBJECT_ID('DeviceEvents'))
--     DROP INDEX [FILL_IN_FROM_PRE_CHECK] ON DeviceEvents;
-- PRINT 'Done.'
-- GO

-- =====================================================
-- AdvanceTrackingSettingSummaries — drop bloated non-clustered indexes
--
-- Same process as DeviceEvents above — review Section 5 output from
-- 01-pre-check-validation.sql and add DROP blocks for each bloated index.
-- =====================================================

-- Example block (copy and repeat for each bloated index found):
-- PRINT 'Dropping [FILL_IN_FROM_PRE_CHECK] on AdvanceTrackingSettingSummaries...'
-- IF EXISTS (SELECT 1 FROM sys.indexes
--            WHERE name = '[FILL_IN_FROM_PRE_CHECK]'
--              AND object_id = OBJECT_ID('AdvanceTrackingSettingSummaries'))
--     DROP INDEX [FILL_IN_FROM_PRE_CHECK] ON AdvanceTrackingSettingSummaries;
-- PRINT 'Done.'
-- GO

-- =====================================================
-- Verification: confirm all targeted indexes have been dropped
-- =====================================================
PRINT '=== Remaining non-clustered indexes on DeviceSummaries ==='
SELECT i.name, i.type_desc,
    CAST(ROUND(SUM(a.total_pages) * 8.0 / 1024 / 1024, 2) AS DECIMAL(18,2)) AS SizeGB
FROM sys.indexes i
JOIN sys.partitions p
    ON i.object_id = p.object_id AND i.index_id = p.index_id
JOIN sys.allocation_units a
    ON p.partition_id = a.container_id
WHERE OBJECT_NAME(i.object_id) = 'DeviceSummaries'
  AND i.type > 1   -- non-clustered only
GROUP BY i.name, i.type_desc
ORDER BY SizeGB DESC;
GO

PRINT '=== Remaining non-clustered indexes on DeviceEvents ==='
SELECT i.name, i.type_desc,
    CAST(ROUND(SUM(a.total_pages) * 8.0 / 1024 / 1024, 2) AS DECIMAL(18,2)) AS SizeGB
FROM sys.indexes i
JOIN sys.partitions p
    ON i.object_id = p.object_id AND i.index_id = p.index_id
JOIN sys.allocation_units a
    ON p.partition_id = a.container_id
WHERE OBJECT_NAME(i.object_id) = 'DeviceEvents'
  AND i.type > 1   -- non-clustered only
GROUP BY i.name, i.type_desc
ORDER BY SizeGB DESC;
GO

PRINT '=== Remaining non-clustered indexes on AdvanceTrackingSettingSummaries ==='
SELECT i.name, i.type_desc,
    CAST(ROUND(SUM(a.total_pages) * 8.0 / 1024 / 1024, 2) AS DECIMAL(18,2)) AS SizeGB
FROM sys.indexes i
JOIN sys.partitions p
    ON i.object_id = p.object_id AND i.index_id = p.index_id
JOIN sys.allocation_units a
    ON p.partition_id = a.container_id
WHERE OBJECT_NAME(i.object_id) = 'AdvanceTrackingSettingSummaries'
  AND i.type > 1   -- non-clustered only
GROUP BY i.name, i.type_desc
ORDER BY SizeGB DESC;
GO

PRINT 'Proceed to 03-create-optimized-indexes.sql'
GO
