-- =====================================================
-- Phase 1, Step 2: Drop Bloated Indexes
-- Run during: OFF-HOURS MAINTENANCE WINDOW ONLY
-- Run AFTER: 01-pre-check-validation.sql (save its output first)
-- Expected duration: ~15-30 minutes
-- Risk: LOW — indexes are not data, no rows are modified
-- Rollback: Re-run 05-rollback-recreate-indexes.sql
-- =====================================================

-- Index 1: IX_DeviceSummaries_DeviceId
-- REASON: Contains 26 columns in the key — this is NOT an index,
-- it's a full copy of the table. Every INSERT writes ~24KB to this index.
-- This index was likely auto-generated or added speculatively and never
-- cleaned up. Dropping it will reduce per-ping write amplification by ~15%.
PRINT 'Dropping IX_DeviceSummaries_DeviceId (26 columns)...'
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_DeviceSummaries_DeviceId' AND object_id = OBJECT_ID('DeviceSummaries'))
    DROP INDEX IX_DeviceSummaries_DeviceId ON DeviceSummaries;
PRINT 'Done.'
GO

-- Index 2: nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6 (renumbered from 3)
-- REASON: Contains 20 columns. Overlaps heavily with the other bloated
-- indexes. Auto-generated by the Azure SQL workload advisor based on a
-- query that was likely a one-time report. The query patterns it served
-- are now covered by the retained indexes and the new optimized index.
PRINT 'Dropping nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6 (20 columns)...'
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6' AND object_id = OBJECT_ID('DeviceSummaries'))
    DROP INDEX nci_wi_DeviceSummaries_DDD72ECE7AF305F90C5D1276C40FA2C6 ON DeviceSummaries;
PRINT 'Done.'
GO

-- Index 3: nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1 (renumbered from 4)
-- REASON: Single column index on ExcursionTimeRunning only — likely from
-- one-off query tuning. Not used by any stored procedure regularly.
-- Queries filtering by ExcursionTimeRunning alone have no selective compound
-- key to leverage; the clustered PK is sufficient for such ad-hoc lookups.
PRINT 'Dropping nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1 (ExcursionTimeRunning only)...'
IF EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1' AND object_id = OBJECT_ID('DeviceSummaries'))
    DROP INDEX nci_wi_DeviceSummaries_B3EAFC8EB862D751B8E12B44239366B1 ON DeviceSummaries;
PRINT 'Done.'
GO

PRINT 'All 3 bloated indexes dropped successfully.'
PRINT 'Proceed to 03-create-optimized-index.sql'
GO
